### ISSUE TITLE
ingress gateway not working

### ISSUE THREAD

**Issue by sachitaggarwal** [kyma-project/kyma#1485]
**Description**
Hi

I followed guide [here](https://github.com/kyma-project/kyma/blob/master/docs/kyma/docs/032-inst-gke-installation.md) to setup kyma on google k8s cluster.

My cluster is up and running and status is installed , but ingress type services  are in 'creating ingress' state and i see error - 
```
Error during sync: error while evaluating the ingress spec: service "kyma-integration/ec-default-event-service-external-api" is type "ClusterIP", expected "NodePort" or "LoadBalancer"; service "kyma-integration/metadata-service-external-api" is type "ClusterIP", expected "NodePort" or "LoadBalancer" 
```

Any suggestions how to fix this issue ?

Best Regards
Sachit

**Comment by lszymik** [comment]
Hello @sachitaggarwal,

I will investigate what is going on. I will need to get more details:
- Are you using release or you are building from `latest` or `master`?
- Can you share how you created a GKE cluster? Which exact version you are using?
- Did you apply any modification to Kyma before deployment?

Thank you in advance, cheers
Lukasz

**Comment by sachitaggarwal** [comment]
Hello Lukasz

I took kyma cluster deployment file from [here](https://github.com/kyma-project/kyma/releases/download/0.4.3/kyma-config-cluster.yaml) , released version 0.4.3

I created gke cluster using command - 
gcloud beta container --project "$PROJECT" clusters \
create "$CLUSTER_NAME" --zone "europe-west1-b" \
--cluster-version "1.10.7-gke.6" --machine-type "n1-standard-2" \
--addons HorizontalPodAutoscaling,HttpLoadBalancing,KubernetesDashboard

No i made no custom changes to kyma software 

Best Regards
Sachit

**Comment by Szymongib** [comment]
We have deployed the cluster following the instructions and everything seems to work as it should.

Could you please provide some more details where exactly you can see the error message?

**Comment by lszymik** [comment]
Hello @sachitaggarwal,
We will need to get additional information from you. We were not able to reproduce it today.

Cheers
Lukasz

**Comment by sachitaggarwal** [comment]
Hello Colleagues

I tried setting up fresh cluster again and i still see ec-default-gateway and hmc-default-gateway in "creating" state
and when i check more details i see same error - 
Error during sync: error while evaluating the ingress spec: service "kyma-integration/ec-default-event-service-external-api" is type "ClusterIP", expected "NodePort" or "LoadBalancer"; service "kyma-integration/metadata-service-external-api" is type "ClusterIP", expected "NodePort" or "LoadBalancer"

All other services are working fine and installation state is successful

Regards
Sachit

**Comment by lszymik** [comment]
After the discussion we decided to reopen that issue.
