### ISSUE TITLE
Unreferenced variable in nodejs serverless function

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#18047]
**Description**

Node.js functions should properly send response even if the response payload is neither of type `string` nor `object`.
Currently for this corner case it falls into unreferenced variable `result` error.

**Comment by kwiatekus** [comment]
Fixed in 2.18

**Comment by janpospisil-sap** [comment]
Issue is still present.

![image](https://github.com/kyma-project/kyma/assets/98947385/ce5e85b7-0da6-4cf4-a702-d285ded539f8)

**Comment by janpospisil-sap** [comment]
Please build another image.
